# GAME MODEL 

TARGETS = {
    0: {"name": "Database Server (Customer PII)",
        "asset_value_millions": 4.88,
        "cvss_confidentiality": "High",
        "cvss_integrity": "High",
        "cvss_availability": "Low"},
    1: {"name": "Web Application (E-commerce)",
        "asset_value_millions": 3.50,
        "cvss_confidentiality": "High",
        "cvss_integrity": "High",
        "cvss_availability": "High"},
    2: {"name": "Email Gateway (Exchange/O365)",
        "asset_value_millions": 2.10,
        "cvss_confidentiality": "High",
        "cvss_integrity": "Low",
        "cvss_availability": "Low"},
    3: {"name": "Active Directory / IAM",
        "asset_value_millions": 5.20,
        "cvss_confidentiality": "High",
        "cvss_integrity": "High",
        "cvss_availability": "High"},
    4: {"name": "VPN / Remote Access Gateway",
        "asset_value_millions": 2.80,
        "cvss_confidentiality": "High",
        "cvss_integrity": "Low",
        "cvss_availability": "High"},
    5: {"name": "Cloud Storage (S3/Blob)",
        "asset_value_millions": 4.10,
        "cvss_confidentiality": "High",
        "cvss_integrity": "High",
        "cvss_availability": "Low"},
    6: {"name": "SCADA/ICS Control System",
        "asset_value_millions": 4.70,
        "cvss_confidentiality": "Low",
        "cvss_integrity": "High",
        "cvss_availability": "High"},
    7: {"name": "DNS Infrastructure",
        "asset_value_millions": 1.90,
        "cvss_confidentiality": "Low",
        "cvss_integrity": "High",
        "cvss_availability": "High"},
}

N_TARGETS = len(TARGETS)

ATTACKER_TYPES = {
    0: {"name": "Script Kiddie / Opportunistic", "capability": 0.3,
        "motivation": "notoriety", "preferred_attack": "known_exploit",
        "risk_tolerance": 0.2},
    1: {"name": "APT Group (Nation-State)", "capability": 0.95,
        "motivation": "espionage", "preferred_attack": "zero_day",
        "risk_tolerance": 0.8},
    2: {"name": "Insider Threat (Malicious)", "capability": 0.6,
        "motivation": "financial", "preferred_attack": "privilege_escalation",
        "risk_tolerance": 0.4},
    3: {"name": "Ransomware Operator (RaaS)", "capability": 0.7,
        "motivation": "ransom", "preferred_attack": "encryption",
        "risk_tolerance": 0.5},
    4: {"name": "Hacktivist Group", "capability": 0.5,
        "motivation": "disruption", "preferred_attack": "ddos_defacement",
        "risk_tolerance": 0.6},
    5: {"name": "Cybercriminal Syndicate", "capability": 0.8,
        "motivation": "data_theft", "preferred_attack": "supply_chain",
        "risk_tolerance": 0.5},
}
N_ATTACKER_TYPES = len(ATTACKER_TYPES)

DEFENDER_RESOURCES = {
    0: {"name": "IDS/IPS Sensor Array",
        "can_cover": [0, 1, 4, 7], "coverage_quality": 0.85},
    1: {"name": "SOC Analyst Team (Tier 1-2)",
        "can_cover": [0, 1, 2, 3, 5], "coverage_quality": 0.75},
    2: {"name": "EDR / XDR Platform",
        "can_cover": [0, 2, 3, 5], "coverage_quality": 0.80},
    3: {"name": "OT Security Monitor",
        "can_cover": [6, 7], "coverage_quality": 0.70},
}
N_RESOURCES = len(DEFENDER_RESOURCES)
